define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "AuditPageTitle": "Permission Audit",
    "AuditPageSubtitle": "Configure the audit scope and review the results.",
    "AuditOptionsLabel": "Audit options",
    "AuditGroupedViewToggleLabel": "Grouped",
    "AuditPrincipalSearchLabel": "Find access for a user or group",
    "AuditPrincipalSearchPlaceholder": "Enter a user or group name",
    "AuditPrincipalSearchButtonLabel": "Search",
    "AuditPrincipalSearchClearButtonLabel": "Clear",
    "AuditOptionExpandGroups": "Expand groups",
    "AuditOptionIncludeListsWithUniquePermissions": "Include lists with unique permissions",
    "AuditOptionIncludeHiddenListsWithUniquePermissions": "Include hidden lists",
    "AuditOptionIncludeListItemsWithUniquePermissions": "Include list items with unique permissions",
    "StartButtonLabel": "Start",
    "ExportCsvButtonLabel": "Export CSV",
    "AuditLoadingLabel": "Loading permission audit results...",
    "AuditResultsGridAriaLabel": "Permission audit results",
    "AuditDetailsContentAriaLabel": "Selected permission audit details",
    "AuditResultsScopeColumn": "Scope",
    "AuditResultsLocationColumn": "Location",
    "AuditResultsStatusColumn": "Status",
    "AuditResultsDetailsColumn": "Details",
    "AuditResultsDisplayNameColumn": "Display Name",
    "AuditResultsGroupNameColumn": "Group name",
    "AuditResultsPrincipalTypeColumn": "Type",
    "AuditResultsGroupPathColumn": "Group path",
    "AuditResultsTypeOfGroupColumn": "Type of group",
    "AuditResultsPermissionLevelsColumn": "Permission levels",
    "AuditResultsOwnerColumn": "Owner",
    "AuditResultsHiddenInUiColumn": "Hidden",
    "AuditResultsMembersCanEditColumn": "Members can edit",
    "AuditGroupTypeOwners": "Owners",
    "AuditGroupTypeMembers": "Members",
    "AuditGroupTypeVisitors": "Visitors",
    "AuditGroupTypeSharePointGroup": "SharePoint group",
    "AuditPrincipalTypeDistributionList": "Distribution list",
    "AuditPrincipalTypeMicrosoft365Group": "Microsoft 365 group",
    "AuditPrincipalTypeSecurityGroup": "Security group",
    "AuditPrincipalTypeList": "List",
    "AuditPrincipalTypeListItem": "List item",
    "AuditPrincipalTypeSite": "Site",
    "AuditPrincipalTypeUnknown": "Unknown",
    "AuditPrincipalTypeUser": "User",
    "AuditUserCountSingular": "user",
    "AuditUserCountPlural": "users",
    "AuditDirectPermissionsGroupLabel": "Direct permissions",
    "AuditGroupNoDirectPermissions": "No direct permissions",
    "AuditGroupYes": "Yes",
    "AuditGroupNo": "No",
    "AuditGroupDetailsHeading": "Group details",
    "AuditGroupDetailsIdLabel": "Id",
    "AuditGroupDetailsLoginNameLabel": "Login name",
    "AuditGroupDetailsDescriptionLabel": "Description",
    "AuditGroupDetailsOwnerLabel": "Owner",
    "AuditGroupDetailsPermissionsLabel": "Permission levels",
    "AuditGroupDetailsMembershipLabel": "Membership",
    "AuditGroupDetailsPathLabel": "Path",
    "AuditGroupDetailsExpansionErrorLabel": "Expansion error",
    "AuditGroupDetailsEmailLabel": "Email",
    "AuditGroupDetailsUserPrincipalNameLabel": "User principal name",
    "AuditPrincipalSearchResultsHeading": "Access search results",
    "AuditPrincipalSearchNoResults": "No matching access was found in the loaded audit results.",
    "AuditPrincipalSearchScopeColumn": "Access scope",
    "AuditPrincipalSearchAccessViaColumn": "Access via",
    "AuditObjectDetailsItemCountLabel": "Item count",
    "AuditObjectDetailsItemIdLabel": "Item id",
    "AuditObjectDetailsUrlLabel": "Url",
    "AuditExportKeyColumn": "Key",
    "AuditExportSourceTypeColumn": "Source type",
    "AuditExportDepthColumn": "Depth",
    "AuditExportParentKeyColumn": "Parent key",
    "AuditExportAadObjectIdColumn": "Entra object id",
    "AuditExportBaseTemplateColumn": "Base template",
    "AuditExportJobTitleColumn": "Job title",
    "AuditExportDepartmentColumn": "Department",
    "AuditExportAdditionalDetailsColumn": "Additional details",
    "AuditGroupDetailsMembersCanEditLabel": "Members can edit membership",
    "AuditGroupDetailsMembersOnlyLabel": "Only members can view membership",
    "AuditGroupDetailsRequestsLabel": "Join and leave requests",
    "AuditGroupDetailsRequestEmailLabel": "Request email",
    "AuditDetailsEmptyValue": "Not available",
    "AuditDetailsOverviewSection": "Overview",
    "AuditDetailsAccessSection": "Access",
    "AuditDetailsIdentitySection": "Identity",
    "AuditDetailsMembershipSection": "Membership",
    "AuditDetailsObjectSection": "Object details",
    "AuditDetailsDirectorySection": "Directory details",
    "AuditDetailsAdditionalSection": "Additional details",
    "AuditDetailsPathValueSeparator": " > ",
    "AuditDetailsTagsLabel": "Tags",
    "AuditDetailsInheritedFromLabel": "Inherited from",
    "AuditDetailsSourceTypeLabel": "Source type",
    "AuditDetailsDepthLabel": "Depth",
    "AuditDetailsParentKeyLabel": "Parent key",
    "AuditDetailsDirectChildrenLabel": "Direct children",
    "AuditDetailsObjectTypeSite": "Site",
    "AuditDetailsObjectTypeList": "List or library",
    "AuditDetailsObjectTypeListItem": "List item",
    "AuditDetailsObjectTypeSharePointGroup": "SharePoint group",
    "AuditDetailsObjectTypeDirectoryGroup": "Directory group",
    "AuditDetailsObjectTypeUser": "User",
    "AuditDetailsObjectTypePrincipal": "Principal",
    "AuditSplitResizeHandleAriaLabel": "Resize results and details panels",
    "AuditGroupFetchError": "Unable to load SharePoint groups."
  }
});
